export const IconMappings = {
    POWER: 'material-symbols-light:power-settings-new',
    POWER_ON: 'material-symbols-light:power-plug-outline',
    POWER_OFF: 'material-symbols-light:power-plug-off-outline',
    SLEEP: 'mdi:power-sleep',
    DISPLAY: 'material-symbols-light:display-settings-outline',
    DIMMER: 'material-symbols-light:brightness-4-outline',
    OPEN_CLOSE: 'material-symbols-light:bottom-panel-open-outline',

    VOLUME_UP:'material-symbols-light:volume-up-outline',
    VOLUME_DOWN:'material-symbols-light:volume-down-outline',
    MUTE:'material-symbols-light:volume-mute-outline',
    TEST_TONE: 'material-symbols-light:music-note',
    BASS_BOOST: 'ri:sound-module-line',
    BALANCE_LEFT: 'solar:airbuds-left-outline',
    BALANCE_RIGHT: 'solar:airbuds-right-outline',
    SPEAKER_A_ON: 'material-symbols-light:speaker-outline',
    SPEAKER_B_ON: 'material-symbols-light:speaker-outline',
    SPEAKERS_OFF: 'mdi:speaker-off',

    MENU: 'material-symbols-light:menu-rounded',
    UP: 'material-symbols-light:arrow-upward-alt-rounded',
    DOWN: 'material-symbols-light:arrow-downward-alt-rounded',
    LEFT: 'material-symbols-light:arrow-left-alt-rounded',
    RIGHT: 'material-symbols-light:arrow-right-alt-rounded',
    ENTER: 'ion:enter-outline',
    RETURN: 'lets-icons:return-light',
    EXIT: 'solar:exit-linear',
    TITLE_MENU: 'material-symbols-light:menu-book-outline',
    DVD_MENU: 'cbi:dvd',

    PLAY: 'material-symbols-light:play-arrow',
    PAUSE: 'material-symbols-light:pause',
    STOP: 'material-symbols-light:stop',
    RECORD: 'material-symbols-light:fiber-manual-record',
    REWIND: 'material-symbols-light:fast-rewind',
    FAST_FORWARD: 'material-symbols-light:fast-forward',
    PREV_TRACK: 'material-symbols-light:skip-previous',
    NEXT_TRACK: 'material-symbols-light:skip-next',
    SLOW_REV: 'solar:rewind-back-circle-broken',
    SLOW_FWD: 'solar:rewind-forward-circle-broken',

    INPUT_TUNER: 'mdi:radio-fm',
    INPUT_CD: 'fluent:cd-16-regular',
    INPUT_PHONO: 'icon-park-outline:phonograph',
    INPUT_DVD: 'tdesign:dvd',
    INPUT_TAPE: 'mdi:tape',
    INPUT_AUX: 'mdi:audio-input-stereo-minijack',
    INPUT_VIDEO1: 'solar:video-frame-bold',
    INPUT_VIDEO2: 'solar:video-frame-bold-duotone',
    INPUT_VIDEO3: 'solar:video-frame-linear',
    INPUT_TV_VIDEO: 'material-symbols-light:tv-outline',

    DIGIT_0: 'fad:digital0',
    DIGIT_1: 'fad:digital1',
    DIGIT_2: 'fad:digital2',
    DIGIT_3: 'fad:digital3',
    DIGIT_4: 'fad:digital4',
    DIGIT_5: 'fad:digital5',
    DIGIT_6: 'fad:digital6',
    DIGIT_7: 'fad:digital7',
    DIGIT_8: 'fad:digital8',
    DIGIT_9: 'fad:digital9',

    PRESET_UP: 'solar:list-up-linear',
    PRESET_DOWN: 'solar:list-down-linear',
    SCAN_UP: 'solar:arrow-up-broken',
    SCAN_DOWN: 'solar:arrow-down-broken',
    TUNING_MODE: 'material-symbols-light:settings-input-antenna',
    BAND: 'f7:antenna-radiowaves-left-right',
    MEMORY: 'material-symbols-light:memory-outline-rounded',
    SHIFT: 'material-symbols-light:keyboard-command-key',

    SOUND_FIELD_ON_OFF: 'material-symbols-light:sound-detection-glass-break-outline-rounded',
    MODE_2CH: 'mdi:stereo',
    MODE_HALL: 'temaki:room',
    MODE_JAZZ: 'qlementine-icons:guitar-classical-24',
    MODE_THEATER: 'game-icons:theater',
    MODE_DISCO: 'ph:disco-ball-light',
    MODE_CHURCH: 'material-symbols-light:church-outline',
    MODE_STADIUM: 'material-symbols-light:stadium-outline',
    MODE_DOLBY: 'mdi:dolby',
    MODE_CINEMA: 'mdi:cinema',
    MODE_MUSIC: 'mdi:music',
    MODE_AFD: 'fluent:sound-wave-circle-sparkle-20-regular',
    MODE_NIGHT: 'tdesign:fog-night',
    MULTI_CH: 'material-symbols-light:surround-sound-outline',
    INPUT_MODE_CHANGE: 'material-symbols:settings-input-component-rounded',

    EQ_ON_OFF: 'carbon:equalizer',
    EQ_SLOPE: 'qlementine-icons:eq-medium-boost-16',
    EQ_CHANNEL: 'material-symbols-light:wifi-channel-outline-rounded',
    LEVEL_UP: 'cil:level-up',
    LEVEL_DOWN: 'cil:level-down',
    FREQ_UP: 'octicon:fold-up-24',
    FREQ_DOWN: 'octicon:fold-down-24',
    REAR_LEVEL_UP: 'lsicon:volume-up-outline',
    REAR_LEVEL_DOWN: 'lsicon:volume-down-outline',
    CENTER_LEVEL_UP: 'lsicon:volume-up-outline',
    CENTER_LEVEL_DOWN: 'lsicon:volume-down-outline',
    SUBWOOFER_LEVEL_UP: 'lsicon:volume-up-outline',
    SUBWOOFER_LEVEL_DOWN: 'lsicon:volume-down-outline',

    AUDIO_CHANGE: 'material-symbols-light:edit-audio',

    STEP_REV: 'solar:rewind-10-seconds-back-broken',
    STEP_FWD: 'solar:rewind-10-seconds-forward-broken',
    REPLAY: 'material-symbols-light:replay-rounded',
    REPEAT: 'material-symbols-light:repeat-rounded',
    CLEAR: 'lsicon:clear-outline',

    SUBTITLE: 'material-symbols-light:subtitles-outline-rounded',
    ANGLE: 'proicons:angle',
    TIME_TEXT: 'mdi:clipboard-text-time-outline',
    SEARCH_MODE: 'material-symbols-light:search-rounded',
    PICTURE_MODE: 'fluent-mdl2:picture-position',
    SURROUND_MODE: 'material-symbols-light:surround-sound-rounded'
}